### PR TITLE
2236 BL files in new format to satisfy both FIHRIST and BL IAMS system

### PR DESCRIPTION
**Pull request by cookjools**
Main types of change involved:

insert <?altova_spc ...\msdesc.sps?> comment (should not affect FIHRIST)

calendar attributes lose # thus #Gregorian becomes Gregorian

two BL-specific altIdentifier elements introduced one with IAMS-ID and the other with MDARK (no need for them to be display on FIHRIST)

author and author/persName key attributes modified when a VIAF number is known: instead of previous person_1234 we now use viaf_1234 (which FIHRIST should interpret as a pseudonym for the same thing). This is to enable both FIHRIST and BL IAMS to use separate authority systems based on the same data.

Tags with empty content are abbreviated, eg.  <textClass></textClass> becomes <textClass />

### CODE REVIEW

**Comment by andrew-morrison** [comment]
The _xml:id_ attribute of the root _TEI_ element has been removed from the following 58 records:
```
Uk_Delhi_Persian_1003.xml	manuscript_3168
Uk_Delhi_Persian_1053.xml	manuscript_18535
Uk_Delhi_Persian_44.xml	manuscript_3233
Uk_IO_Islamic_3920.xml	manuscript_17962
Uk_IO_Islamic_3932.xml	manuscript_17975
Uk_IO_Islamic_4506.xml	manuscript_18278
Uk_Or_10007.xml	manuscript_5175
Uk_Or_10043.xml	manuscript_5176
Uk_Or_10193.xml	manuscript_5177
Uk_Or_10194.xml	manuscript_5178
Uk_Or_10195.xml	manuscript_5179
Uk_Or_10196.xml	manuscript_5180
Uk_Or_10397.xml	manuscript_5181
Uk_Or_10427.xml	manuscript_5182
Uk_Or_10444.xml	manuscript_5183
Uk_Or_10482.xml	manuscript_5184
Uk_Or_10556.xml	manuscript_5185
Uk_Or_10576.xml	manuscript_5186
Uk_Or_10577.xml	manuscript_5187
Uk_Or_10711.xml	manuscript_5188
Uk_Or_10773.xml	manuscript_5189
Uk_Or_10774.xml	manuscript_5190
Uk_Or_10775.xml	manuscript_5191
Uk_Or_12189.xml	manuscript_5480
Uk_Or_12190.xml	manuscript_5481
Uk_Or_12191.xml	manuscript_5482
Uk_Or_13189.xml	manuscript_5546
Uk_Or_13190.xml	manuscript_5547
Uk_Or_13704.xml	manuscript_5578
Uk_Or_13872.xml	manuscript_5607
Uk_Or_13913.xml	manuscript_5612
Uk_Or_13914.xml	manuscript_5613
Uk_Or_14594.xml	manuscript_5694
Uk_Or_14595.xml	manuscript_5695
Uk_Or_14596.xml	manuscript_5696
Uk_Or_2451.xml	manuscript_5895
Uk_Or_2452.xml	manuscript_5896
Uk_Or_2453.xml	manuscript_5897
Uk_Or_2454.xml	manuscript_5898
Uk_Or_2455.xml	manuscript_5899
Uk_Or_2456.xml	manuscript_5900
Uk_Or_2459.xml	manuscript_5901
Uk_Or_2460.xml	manuscript_5902
Uk_Or_4729.xml	manuscript_5922
Uk_Or_4730.xml	manuscript_5923
Uk_Or_4731.xml	manuscript_5924
Uk_Or_4732.xml	manuscript_5925
Uk_Or_4742.xml	manuscript_5926
Uk_Or_4743.xml	manuscript_5927
Uk_Or_4744.xml	manuscript_5928
Uk_Or_4745.xml	manuscript_5929
Uk_Or_5446.xml	manuscript_5968
Uk_Or_8212_166.xml	manuscript_6354
Uk_Or_8659.xml	manuscript_6417
Uk_Or_8695.xml	manuscript_6422
Uk_Or_9804.xml	manuscript_6529
Uk_Or_9884.xml	manuscript_6557
Uk_Or_9953.xml	manuscript_6558
```

**Comment by cookjools** [comment]
Yikes - very sorry Andrew - will get onto those this evening - can not guess how that happened - have been against the clock on some internal bl authority stuff this pm so didnt catch your email until now - thanks for being suoer efficient as ever - and apologies again

Best, Julian
________________________________

**Comment by cookjools** [comment]
Hi Andrew

I believe I have now remedied the situation on the new branch. I had stupidly introduced some IAMS TEI records which have been independently catalogued by a Hebrew curator – hence the lack of manuscript id in the TEI header. My code to avoid doing that had a stupid bug.

Anyway, I rebuilt the set of 2626 files by reverting to the master and then overwriting only those I should with IAMS TEI ‘master’ records which have been modified to work in both IAMS and FIHRIST (a total of 2174 of them). Every record should maintain its old manuscript id.

While I was doing this, I discovered 4 files I thought I had renamed on the master branch did not reflect the change (I suspect because Github desktop does not regard a change of case in a filename as any change at all). To get around this I made a pair of commits on the master branch, adding _RENAME to the filenames and then removing it. Et voila. The same case switch in the 4 file names is reflected in the development branch, but I believe this will appear as a conflict when we come to merge the branches given I made the same change independently on the two branches. Should be very easy to deal with – only 4 files after all.

I hope you are now able to run your tests on the person_ to viaf_ changes and so on.

Many thanks – and apologies for the delay while I sorted out my stupidity with the doubly-catalogued records. Needless to say the double cataloguing of manuscripts with mixed content (Persian/Hebrew or Persian/Arabic) is something I will have to resolve at a later date, if we are truly to have a single master record in both IAMS and FIHRIST.

All the best

Julian

**Comment by andrew-morrison** [comment]
The indexer will now run successfully on the files in this branch. However there is another smaller problem, but one which causes enough differences to make it difficult to see the effects of other changes. Some but not all _persName_ elements with _role_ attributes containing multiple values are now delimited with underscores instead of spaces.

For example, in Uk_IO_Islamic_4762.xml, what was...
```
<persName xml:lang="fa-Latn-x-lc" type="standard" key="person_f4828" role="aut scr" change="#role-assignment">ʻAzīz al-Dīn Aḥmad ʻUẓāmī, 1898-1957</persName>
```
...has now become...
```
<persName xml:lang="fa-Latn-x-lc" type="standard" key="person_f4828" role="aut_scr" change="#role-assignment">ʻAzīz al-Dīn Aḥmad ʻUẓāmī, 1898-1957</persName>
```
Which means that instead of the roles listed on [this page](https://www.fihrist.org.uk/catalog/person_f4828) being...

> Author, Scribe

...it'll be replaced with...

> Aut_scr, Author

If you can fix those, and commit them to this branch, then I'll try re-indexing again, on Monday.

Also, because you have renamed four BL files on the master branch which you've also modified on this branch, they are now conflicts which will need to be resolved before this pull request can be merged. It would be best to delay other changes until the merge is done. But, for future reference, you can rename files in one step if you have command-line Git tools installed. For example...
```
git mv Uk_Add_Ms_21471.xml Uk_Add_MS_21471.xml
```
That should avoid any issues due to [case-sensitivity differences between operating systems](https://en.wikipedia.org/wiki/Case_sensitivity#In_filesystems).

**Comment by cookjools** [comment]
Hi Andrew - my latest commit to this branch should have fixed the underscore instead of space problem in @role attributes. (I had forgotten I had introduced those to satisfy the old schema in BL's IAMS system - and had neglected to reverse this when we went over to the new schema). 

However, I also noticed something else which might cause your new scripts to object (I really hope not). Numerous BL records contain persName elements with @key values containing not only the new viaf_1234 but also a space separated ark:... . value.  Your scriptsshould ignore the arks. I hope that is not a big problem - I am hoping your code already ignores exceptions to person_ and viaf_, but I am very sorry if you need to make yet more changes. 

I am afraid there is nothing much I can do about these ark's - the BL IAMS system inserts them into the TEI master record (although for some reason there seems to be a delay in it doing so - something like 524 BL records now use them).

For example, see Uk_Delhi_Persian_1177 which contains:

<persName key="ark:/81055/vdc_100164656324.0x000001 viaf_11716360" type="supplied" xml:lang="per-Latn-x-lc">Charkhī, Yaʿqūb, -1447</persName>

**Comment by andrew-morrison** [comment]
I've made some script adjustments to handle BL ARKs in `@key` attributes. I'll commit those changes when you've merged this branch. It would be better if they were in `@ref` attributes, in their full URL form, as that would mean someone doing digital scholarship analysis in the future would (a) know what they are, and (b) could potentially enhance their data with whatever information they get by resolving the ARK URL. As it is, they are pretty meaningless to anyone outside the BL. But, if you are OK with that, then it doesn't bother me.

The number of differences observed when re-indexing from this branch versus the master branch has reduced. But I have spotted another problem. Some, but not all, of the `@calendar` attributes in the BL records now have a value of "Hijri qamari", with a space between the two words. In your Word document proposal you said you'd be changing "#Hijri-qamari" to "Hijri-qamari", so that's what I changed the scripts to expect. I'd advise changing your data, rather than my indexing scripts, as according to the TEI specs `@calendar` values can be space-separated, so strictly-speaking `calendar="Hijri qamari"` is saying the text of the element is expressing the date in two calendars, "Hijri" and "qamari", which makes no sense.

Here are the various values for `@calendar` which currently exist in BL records (including `date` elements, not just `origDate`):

| Calendar attribute value | Number of instances |
| ------ | ------ |
| Gregorian | 4038 |
| Hijri qamari | 2119 |
| #Gregorian | 741 |
| #Hijri-qamari | 391 |
| #other | 126 |
| Bengali fasli | 64 |
| Hijri shamsi | 29 |
| #AM | 11 |
| #Hijri-shamsi | 4 |
| #Hindu | 3 |
| #Hijri-qamar | 2 |
| Vikrama | 1 |
| #otheri | 1 |
| Hijri-qamari | 1 |
| #Gregoriani | 1 |
| #Bengali-Fasli | 1 |

**Comment by cookjools** [comment]
What a horrible mess - am very sorry Andrew. Am pretty sure these are the kind of things I fixed at some point so can not explain there reappearance. There are clearly issues with the loop I have been going around, getting batch edits into IAMS and back out the next day, and finally transferring the master record across to FIHRIST. 

Anyway.... so as to clean up the data in this branch of FIHRIST quickly - allowing you to perform a reindex and test things once again - I have just made a set of fixes directly to the FIHRIST data itself (on this branch; ignoring the problems with IAMS for now).

The data on this branch should now contain only the following @calendar values:

Gregorian
Hijri-qamari
Hijri-shamsi
AM
Other
Bengali-fasli
Vikrama
Hindu

The XQuery script I have used resulted in another change - removing space prior to closing of a tag with no text content, e.g.

e.g. <incipit xml:lang="fa" /> becomes <incipit xml:lang="fa"/>

This means every single file will have changed in this last commit.

**Comment by cookjools** [comment]
Andrew, in response to your comments regrading the Arks I am afraid there is nothing I can do about how BL has designed its authority system. It is at best opaque and partially implemented - I am unable to determine the logic by which some persName elements with a viaf number have an Ark inserted alongside that, while others do not. For I am not granted access to the code and must treat it as a very quirky black box. What is more, further development of the way BL systems handle TEI is out of the question in the short to medium term. At some point they hope a new system will appear and solve all known problems - but that is many years away at best. In these circumstances, what you are doing to allow a single record to function in both places is extremely valuable, and is much appreciated.

**Comment by andrew-morrison** [comment]
I've tested the indexing process again, and there are just a couple of small issues:

 * Uk_IO_Islamic_3925.xml has changed its `/TEI/@xml:id` from "manuscript_17968" to "manuscript_17967". The new ID hasn't been used elsewhere (at least not in this branch on this repository) so that is OK. But it means someone who [finds it by googling](https://www.google.com/search?q="IO+Islamic+3925") will get a 404 page until they update their indexes (which might take a few weeks.)
 * Uk_Delhi_Persian_1040A.xml, Uk_Delhi_Persian_1104B.xml, Uk_Delhi_Persian_1104B.xml, Uk_Delhi_Persian_1104C.xml, and Uk_Delhi_Persian_1104D.xml each contain a `@key` referencing "person_f7024". Yasmin edited those files on 20/10/2022, replacing the key value with [person_220725873](https://www.fihrist.org.uk/catalog/person_220725873), because she reckoned they were the same person, and a VIAF-based entry is preferred. If you disagree, you should talk to Yasmin about reinstating that authority entry (there's a copy in persons_deletions.xml.) If you agree, presumably the attributes should be changed to "viaf_220725873" and the master copies of those records updated in IAMS (or do changes only go one-way?)

Apart from that, and the few fixed language codes you previously mentioned, there are just insignificant style changes. Things like multiple hyperlinks instead of one (when the `@key` has been moved from `author` to child `persName` elements) and a few places where the removal of an empty TEI element has slightly changed the line-spacing.

**Review by andrew-morrison — APPROVED** [review]

**Comment by jamescummings** [comment]
Hiya, 

Not trying to throw a spanner in the works, but please also note that the `@calendar` attribute in TEI is a datatype of teidata.pointer meaning that it is a URI. c.f. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.html#tei_att.calendar 

So if you have an attribute value of 'Hijri qamari' you are saying that there is a physical file on disk there called 'Hijri' and another called 'qamari'. If you have a value like 'Gregorian' without a number sign you are saying there is a file on disk there local to the description called 'Gregorian'. The '#Gregorian' version with the hash as a URI fragment means that there is an xml:id of 'Gregorian' somewhere in the document (preferably on a `<calendar>` element in the header describing that calendaring system). 

Of course I could be entirely misunderstanding what you are doing as I only stick my head in to lurk occasionally. ;-)  

-James

**Comment by cookjools** [comment]
Thanks for the input, James – you are right of course. The space in the calendar attribute was an unintended data error hopefully now fixed. The hash before the calendars certainly implied there would be a calendar element somewhere but as far as I know no one ever inserts those into FIHRIST records so the hash is rather redundant. More importantly, for current purposes (bringing British Library systems into alignment with FIHRIST around a single master record) BL systems have other records using the same calendars but without the hash. So it seems a bit perverse to introduce hash variants in order to support a FIHRIST usage which is never fully implemented. Andrew has kindly amended his scripts to allow the hash to be omitted.

All the best,

Julian

**Comment by cookjools** [comment]
Merging branch with BL specific modifications to VIAF numbers (person_123 becomes viaf_123) and associated changes (**bl_new_format_for_viaf_numbers_etc**)  into **master**

**Pull request merged**
