### PR TITLE
Fill blank key attributes in Fihrist records

### PR DESCRIPTION
**Pull request by andrew-morrison**
Hello,

I have written a script which finds blank key attributes (e.g. `<persName key="">Joe Bloggs</persName>`) and searches the local authority files for entries which match the name (or title for works). When it finds a single exact match, it plugs the ID from the authority entry into the key attribute (e.g. `<persName key="person_f1234">Joe Bloggs</persName>`). This is necessary for the person (or work) to get its own page on the Fihrist web site, and for the relevant manuscript(s) to link to those pages, and vice versa.

Because of the nature of XSLT, it also slightly reformats a few things (e.g. converts `<p></p>` to `<p/>`, removes redundant duplicate namespace declarations, etc) but nothing which will affect the content displayed on the Fihrist web site.

I've run this script on all the Fihrist collections, and it found 326 records (out of 13,261) containing blank key attributes it could fill. These are most of the records created in the last couple of years (apart from the Eton and King's Pote collections, because Julian Cook manually looked up the keys himself.) It failed to match 59 of them, and left those as-is. The resulting changes are now in a branch on GitHub, separate from the master branch containing the originals. This pull request will merge them in.

Please click on the link at the bottom of the notification email, then click on the Commits tab, to view the changes. Keeping two versions of these 326 files will risk conflicts, if people edit the same records on the master branch, in the time period between now and when they are merged. So I propose to merge it myself on Friday this week, unless I hear back that you'd like longer to review it. Each institution's files are in a separate commit, so it is possible to opt-out completely if you wish.

Andrew.

### CODE REVIEW

**Comment by eifionjones** [comment]
Looks good to me! Thanks

**Comment by yf227** [comment]
Hi Andrew, thank you for this, that's excellent!! I had a quick look at the files and it looks perfect. shall I review the 59?

**Comment by andrew-morrison** [comment]
Attached is the list of 59 names and titles that couldn't be matched:

[names_and_titles_unmatched_to_authorities.txt](https://github.com/fihristorg/fihrist-mss/files/4408878/names_and_titles_unmatched_to_authorities.txt)

Remember to go to GitHub Desktop first and switch branches, from "master" to the "fill-blank-key-attributess", before working on these blank key attributes.

But for working on anything else, stay on the master branch. It may create a few conflicts, but they aren't a problem over a short period, when it is easy to trace back who did what when merging.

An alternative method to find the blank keys is to right click on the "collections" folder in the project view in Oxygen, select _Find/Replace in Files_, enter `""` in the _Text to find_ field, and `//@key` in _Restrict to XPath_, then click _Find All_.

**Comment by yf227** [comment]
Thanks Andrew!


Yasmin Faghihi
Head of Near and Middle Eastern Department
Manuscripts and Printed Collections
Cambridge University Library
West Road
CB3 9DR UK
Tel.: +44 1223 764739
Email: yf227@cam.ac.uk<mailto:yf227@cam.ac.uk>
Chair
Middle East Libraries COMmittee (MELCOM) UK
http://www.melcom.org.uk/
FIHRIST
http://www.fihrist.org.uk/home
--

**Comment by yf227** [comment]
Hi Andrew, there is a conflict with this file now because of the blank key attributes, but isn't the system generating these normally? What do you advise?
I have a few more files with descriptive titles without id's coming up.
Thanks

**Comment by yf227** [comment]
Sorry!

**Comment by yf227** [comment]
Hi Andrew, as for the 59 stubborn files, let's leave them be for now. We are about to embark on some authority work with Julian (Cook)'s help and can deal with them than. I gather those are genuinely unreferenced authors and works.

**Comment by andrew-morrison** [comment]
I have merged and re-indexed the Fihrist web site with these changes. It has increased the number of indexed works by 376 and the number of indexed people by 228.

**Comment by eifionjones** [comment]
Thanks Andrew, great!
Have a nice weekend – the weather will be good at least
Best,
Huw

**Pull request merged**
