### PR TITLE
BL - two further batches pushed on dedicated branch

### PR DESCRIPTION
**Pull request by julian-cook-bl-uk**
BRANCH: British_Library_additions_June_2023
=============================
Batch 3: 182 manuscripts.
Batch 4: 149 manuscripts.

Also updated versions of
authority/persons_additions.xml [including a block of new persons] authority/persons_base.xml [including refs from newly added mss] authority/works_additions.xml [including a block of new works] authority/works_base.xml [including refs from newly added mss]

### CODE REVIEW

**Comment by andrew-morrison** [comment]
The following need to be fixed before this branch can be merged:

 * Invalid language codes:
   * Uk_Delhi_Persian_1229.xml: `<textLang mainLang="tu" otherLangs="fa">Turkish and Persian</textLang>`
   * Uk_Or_16987_1-35.xml: `<textLang mainLang="ma">Marathi</textLang>`
 * Subjects not using the LCSH/LCNAF authorities which Fihrist supports:
   * Uk_Delhi_Persian_88.xml: `<term key="subject_sj96006319" target="http://lccn.loc.gov/sj96006319#concept">Prayer books and devotions</term>` (uses the children's version of LCSH)
   * Uk_Delhi_Persian_669_star.xml: `<term key="subject_gf2015026087" target="https://lccn.loc.gov/gf2015026087#concept">Litanies</term>` (uses LCGFT)
 * work IDs referenced in key attributes in records but not added to the works authority file:
   * work_21839
   * work_21840
   * work_21841
   * work_21845
   * work_21846
   * work_21849
   * work_21850
   * work_21851
   * work_21852
   * work_21855
   * work_21857
   * work_21858
   * work_21859
   * work_21860
   * work_21861
   * work_21862
   * work_21863
   * work_21865
   * work_21872
   * work_21873
   * work_21875
   * work_21876
   * work_21877
   * work_21879
   * work_21880
   * work_21951
   * work_21992
   * work_22001
   * work_22002
   * work_22004
   * work_22005
   * work_22050
   * work_22099
   * work_22159
   * work_22160
   * work_22161
   * work_22163
   * work_22164
   * work_22165
   * work_22169
   * work_22170
   * work_22172
   * work_22173
 * work IDs that reuse an ID that has previously been deleted
   * work_21720

The last of those will work, but it is a bit confusing, as there is an entry with that ID in works_deletions.xml.

**Comment by julian-cook-bl-uk** [comment]
Hi Andrew

I believe I have now fixed all the problems you discovered on branch British_Library_Additions_June_2023 - and I have just now committed and pushed the fixes.

So could I ask you to assess once more whether the branch is fit to be merged with master, please?

Many thanks for your careful work on this - and apologies for the various glitches.

Very best

Julian

**Comment by andrew-morrison** [comment]
You've fixed everything above, but there are some more issues I didn't notice last time:

 * Uk_Or_13191.xml doesn't have a manuscript ID in  `TEI/@xml:id`. It also lacks schema declarations.
 * Uk_Delhi_Persian_95A.xml contains a bad role attribute: `<persName key="person_f8286" role="38323081">ʿĪsá or Jesus the son of Mary</persName>`
 * Uk_Or_16174.xml lacks a collection, because its msIdentifier contains: `<collection />`
 * There are a lot of other self-closing tags such as `<additions/>`, `<surrogates />`, `<summary/>`,  `<head />`, `<author/>`, `<colophon />`, etc. Perhaps those were placeholders in a template, which the cataloguers didn't delete when they decided they weren't applicable to the manuscript they were describing? Whatever the reason, the consequence is that many of these will display as labels or subheadings on the web site, but with nothing after or underneath them. 
 * The records that do have contents in their surrogates don't follow the [syntax documented here](https://msdesc.github.io/consolidated-tei-schema/msdesc.html#surrogates). Hence they too will appear as "Surrogates" subheadings with nothing beneath them. An example is in Uk_RSPA_215.xml: `<surrogates><bibl><ref type="Digital" target="http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=RSPA_215" /></bibl></surrogates>`

None of these would prevent me from re-indexing the web site. Uk_Or_13191.xml would simply be skipped. And the rest are nothing I wouldn't normally let through during a weekly re-index, and inform the person responsible, so that they can fix them ready for next week. So I am happy to merge this branch. Let me know by 6pm today whether you want me to do so, or you'd prefer to fix the new issues on this branch first, and delay re-indexing till next week?

**Comment by julian-cook-bl-uk** [comment]
Hi Andrew

Many thanks again.

I have fixed the first 3 of these, removing Or 13191 entirely.

We can certainly live with the empty tag / subheadings problem for now and I will have to look further at the surrogates issue to check what is required for internal BL systems. Am happy the cosmetic things would all be fixable at a later date on the main branch.

So, yes please, would you go ahead and merge this branch into master, and kick off a full re-index if there is still time for that this week.

Many thanks for your invaluable help – now wishing you a nice weekend.

Julian

**Pull request merged**
